export const AppConstants = {
  fcmProviderId: '',
  apnsProviderId: '',
  authKey: '',
  appId: '',
  region: '',
  subscriptionType: 'ALL_USERS',
  versionNumber: 'V5.0.1',
};

export const SCREEN_CONSTANTS = {
  APP_CRED: 'AppCredentials',
  SAMPLER_USER: 'SampleUser',
  ONGOING_CALL_SCREEN: 'OngoingCallScreen',
  BOTTOM_TAB_NAVIGATOR: 'BottomTabNavigator',
  CHATS: 'Chats',
  CALLS: 'Calls',
  USERS: 'Users',
  GROUPS: 'Groups',
  CONVERSATION: 'Conversation',
  CREATE_CONVERSATION: 'CreateConversation',
  MESSAGES: 'Messages',
  THREAD_VIEW: 'ThreadView',
  USER_INFO: 'UserInfo',
  GROUP_INFO: 'GroupInfo',
  ADD_MEMBER: 'AddMember',
  TRANSFER_OWNERSHIP: 'TransferOwnershipSection',
  BANNED_MEMBER: 'BannedMember',
  VIEW_MEMBER: 'ViewMembers',
  CALL_LOGS: 'CallLogs',
  CALL_DETAILS: 'CallDetails',
  GROUPS_SCREEN: 'GroupsScreen',
} as const;
